In [1]:
import pandas as pd
DATA = 'data/'
orders = pd.read_csv(DATA + 'olist_orders_dataset.csv', parse_dates=[
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
], date_format = {
    'order_purchase_timestamp': '%m/%d/%y %H:%M',
    'order_approved_at': '%m/%d/%y %H:%M',
    'order_delivered_carrier_date': '%m/%d/%y %H:%M',
    'order_delivered_customer_date': '%m/%d/%y %H:%M',
    'order_estimated_delivery_date': '%m/%d/%y %H:%M',
})

In [2]:
orders.shape

(99441, 8)

In [3]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26

In [4]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [5]:
orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']

0        8 days 10:29:00
1       13 days 18:46:00
2        9 days 09:28:00
3       13 days 05:00:00
4        2 days 20:59:00
              ...
99436    8 days 05:14:00
99437   22 days 04:39:00
99438   24 days 20:38:00
99439   17 days 02:04:00
99440    7 days 16:11:00
Length: 99441, dtype: timedelta64[us]

In [6]:
customers = pd.read_csv(DATA + 'olist_customers_dataset.csv')

In [7]:
customers.shape

(99441, 5)

In [8]:
customers.dtypes

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [9]:
customers['customer_id'].nunique()

99441

In [10]:
df = orders.merge(customers, on = 'customer_id')

In [11]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [12]:
df.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
customer_unique_id                          str
customer_zip_code_prefix                  int64
customer_city                               str
customer_state                              str
dtype: object

In [13]:
df.shape

(99441, 12)

In [14]:
delivered = df[
    (df['order_status'] == 'delivered') &
    (df['order_delivered_customer_date'].notna()) &
    (df['order_purchase_timestamp'] >= '2017-01-01') &
    (df['order_purchase_timestamp'] < '2018-09-01')
    ]

In [15]:
delivered.shape

(96203, 12)

In [16]:
assert delivered.shape[0] == 96203

In [17]:
purchase_date = delivered['order_purchase_timestamp'].dt.normalize()
delivered_date = delivered['order_delivered_customer_date'].dt.normalize()
estimated_date = delivered['order_estimated_delivery_date'].dt.normalize()

delivered['delivery_days'] = (delivered_date - purchase_date).dt.days
delivered['is_late'] = delivered_date > estimated_date
delivered['days_vs_estimate'] = (delivered_date - estimated_date).dt.days
delivered['purchase_month'] = delivered['order_purchase_timestamp'].dt.to_period('M')

In [18]:
assert delivered['delivery_days'].min() == 0
assert delivered['delivery_days'].max() == 210
assert delivered['is_late'].sum() == 6531
assert delivered['delivery_days'].median() == 10
assert delivered['delivery_days'].quantile(0.9) == 23
assert round(delivered['delivery_days'].mean(), 1) == 12.5

In [23]:
delivered['bucket'] = pd.cut(
    delivered['delivery_days'],
    bins=[-1,3,7,14,23,30,60,float('inf')],
    labels=['0-3 дн.','4-7 дн.','8-14 дн.','15-23 дн.','24-30 дн.','31-60 дн.', '61+ дн.']
)

In [29]:
bucketed = delivered.groupby('bucket')['order_id'].size()

bucketed

bucket
0-3 дн.       6952
4-7 дн.      23708
8-14 дн.     37899
15-23 дн.    18573
24-30 дн.     4824
31-60 дн.     3952
61+ дн.        295
Name: order_id, dtype: int64