In [1]:
import pandas as pd
DATA = 'data/'
orders = pd.read_csv(DATA + 'olist_orders_dataset.csv', parse_dates=[
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
], date_format = {
    'order_purchase_timestamp': '%m/%d/%y %H:%M',
    'order_approved_at': '%m/%d/%y %H:%M',
    'order_delivered_carrier_date': '%m/%d/%y %H:%M',
    'order_delivered_customer_date': '%m/%d/%y %H:%M',
    'order_estimated_delivery_date': '%m/%d/%y %H:%M',
})

In [2]:
orders.shape

(99441, 8)

In [3]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26

In [4]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [5]:
orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']

0        8 days 10:29:00
1       13 days 18:46:00
2        9 days 09:28:00
3       13 days 05:00:00
4        2 days 20:59:00
              ...
99436    8 days 05:14:00
99437   22 days 04:39:00
99438   24 days 20:38:00
99439   17 days 02:04:00
99440    7 days 16:11:00
Length: 99441, dtype: timedelta64[us]

In [6]:
customers = pd.read_csv(DATA + 'olist_customers_dataset.csv')

In [7]:
customers.shape

(99441, 5)

In [8]:
customers.dtypes

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [9]:
customers['customer_id'].nunique()

99441

In [10]:
df = orders.merge(customers, on = 'customer_id')

In [11]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [12]:
df.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
customer_unique_id                          str
customer_zip_code_prefix                  int64
customer_city                               str
customer_state                              str
dtype: object

In [13]:
df.shape

(99441, 12)

In [14]:
delivered = df[
    (df['order_status'] == 'delivered') &
    (df['order_delivered_customer_date'].notna()) &
    (df['order_purchase_timestamp'] >= '2017-01-01') &
    (df['order_purchase_timestamp'] < '2018-09-01')
    ]

In [15]:
delivered.shape

(96203, 12)

In [16]:
assert delivered.shape[0] == 96203

In [17]:
purchase_date = delivered['order_purchase_timestamp'].dt.normalize()
delivered_date = delivered['order_delivered_customer_date'].dt.normalize()
estimated_date = delivered['order_estimated_delivery_date'].dt.normalize()

delivered['delivery_days'] = (delivered_date - purchase_date).dt.days
delivered['is_late'] = delivered_date > estimated_date
delivered['days_vs_estimate'] = (delivered_date - estimated_date).dt.days
delivered['purchase_month'] = delivered['order_purchase_timestamp'].dt.to_period('M')
delivered['promise_days'] = (estimated_date - purchase_date).dt.days

delivered

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,delivery_days,is_late,days_vs_estimate,purchase_month,promise_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,8,False,-8,2017-10,16
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,14,False,-6,2018-07,20
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,9,False,-18,2018-08,27
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,14,False,-13,2017-11,27
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,3,False,-10,2018-02,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:00,2017-03-09 09:54:00,2017-03-10 11:18:00,2017-03-17 15:08:00,2017-03-28,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,SP,8,False,-11,2017-03,19
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:00,2018-02-06 13:10:00,2018-02-07 23:22:00,2018-02-28 17:37:00,2018-03-02,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,22,False,-2,2018-02,24
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:00,2017-08-27 15:04:00,2017-08-28 20:52:00,2017-09-21 11:24:00,2017-09-27,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,25,False,-6,2017-08,31
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-12 15:35:00,2018-01-25 23:32:00,2018-02-15,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,17,False,-21,2018-01,38
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:00,2018-03-09 11:20:00,2018-03-09 22:11:00,2018-03-16 13:08:00,2018-04-03,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,8,False,-18,2018-03,26

In [18]:
assert delivered['delivery_days'].min() == 0
assert delivered['delivery_days'].max() == 210
assert delivered['is_late'].sum() == 6531
assert delivered['delivery_days'].median() == 10
assert delivered['delivery_days'].quantile(0.9) == 23
assert round(delivered['delivery_days'].mean(), 1) == 12.5

In [19]:
delivered['bucket'] = pd.cut(
    delivered['delivery_days'],
    bins=[-1,3,7,14,23,30,60,float('inf')],
    labels=['0-3 дн.','4-7 дн.','8-14 дн.','15-23 дн.','24-30 дн.','31-60 дн.', '61+ дн.']
)

In [20]:
bucketed = delivered.groupby('bucket').agg(
    orders_count=('order_id', 'size'),
)
bucketed['cum_orders_count'] = bucketed['orders_count'].cumsum()
bucketed['pct'] = (bucketed['orders_count'] / bucketed['orders_count'].sum() * 100).round(2)
bucketed['cum_pct'] = (bucketed['orders_count'].cumsum() / bucketed['orders_count'].sum() * 100).round(2)

bucketed

           orders_count  cum_orders_count    pct  cum_pct
bucket
0-3 дн.            6952              6952   7.23     7.23
4-7 дн.           23708             30660  24.64    31.87
8-14 дн.          37899             68559  39.39    71.26
15-23 дн.         18573             87132  19.31    90.57
24-30 дн.          4824             91956   5.01    95.59
31-60 дн.          3952             95908   4.11    99.69
61+ дн.             295             96203   0.31   100.00

In [21]:
assert bucketed.loc['8-14 дн.', 'orders_count'] == 37899
assert bucketed.loc['15-23 дн.', 'cum_pct'] == 90.57
assert bucketed['orders_count'].sum() == 96203

In [22]:
group_by_month = delivered.groupby('purchase_month').agg(
    orders_count=('order_id', 'size'),
    late_orders_count=('is_late', 'sum'),
    median_delivery_days=('delivery_days', 'median'),
    p90_delivery_days=('delivery_days', lambda d: d.quantile(0.9)),
    median_promise_days=('promise_days', 'median'),
)
group_by_month['late_orders_pct'] = (group_by_month['late_orders_count'] / group_by_month['orders_count'] * 100).round(2)
group_by_month['cushion_days'] = (group_by_month['median_promise_days'] - group_by_month['p90_delivery_days']).round(0).astype(int)

group_by_month

,orders_count,late_orders_count,median_delivery_days,p90_delivery_days,median_promise_days,late_orders_pct,cushion_days
purchase_month,,,,,,,
2017-01,750,22,11.0,19.0,39.0,2.93,20
2017-02,1653,49,11.0,22.0,31.0,2.96,9
2017-03,2546,116,10.0,21.0,23.0,4.56,2
2017-04,2303,151,13.0,25.0,26.0,6.56,1
2017-05,3545,106,10.0,19.0,24.0,2.99,5
2017-06,3135,95,11.0,20.0,24.0,3.03,4
2017-07,3872,108,10.0,20.0,24.0,2.79,4
2017-08,4193,122,10.0,19.0,23.0,2.91,4
2017-09,4150,182,10.0,20.0,23.0,4.39,3
2017-10,4478,187,10.0,20.0,23.0,4.18,3
2017-11,7288,904,13.0,27.0,23.0,12.40,-4
2017-12,5513,411,13.0,28.0,28.0,7.46,0
2018-01,7069,403,12.0,25.0,26.0,5.70,1
2018-02,6555,926,14.0,31.0,25.0,14.13,-6
2018-03,7003,1328,13.0,32.0,22.0,18.96,-10
2018-04,6798,306,9.0,21.0,24.0,4.50,3
2018-05,6749,443,9.0,21.0,22.0,6.56,1
2018-06,6096,71,8.0,16.0,28.0,1.16,12
2018-07,6156,208,7.0,16.0,20.0,3.38,4
2018-08,6351,393,7.0,13.0,14.0,6.19,1

In [23]:
assert group_by_month['orders_count'].sum() == 96203
assert group_by_month['late_orders_count'].sum() == 6531
assert len(group_by_month) == 20

In [24]:
reviews = pd.read_csv(DATA + 'olist_order_reviews_dataset.csv', parse_dates = [
    'review_creation_date', 
    'review_answer_timestamp',
], date_format = {
    'review_creation_date': '%Y-%m-%d %H:%M:%S',
    'review_answer_timestamp': '%Y-%m-%d %H:%M:%S',
}
)
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

In [25]:
reviews.dtypes

review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [26]:
# orders with more than one review
(reviews['order_id'].value_counts() > 1).sum()

np.int64(547)

In [27]:
reviews['order_id'].nunique()

98673

In [28]:
# keep lastest review of orders
reviews_by_order = reviews.sort_values(['order_id', 'review_creation_date', 'review_id'], ascending=[True, False, False]).drop_duplicates(subset='order_id', keep='first')

In [29]:
orders_reviews = delivered.merge(reviews_by_order, on='order_id', how='left')

orders_reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 96203 entries, 0 to 96202
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96203 non-null  str
 1   customer_id                    96203 non-null  str
 2   order_status                   96203 non-null  str
 3   order_purchase_timestamp       96203 non-null  datetime64[us]
 4   order_approved_at              96189 non-null  datetime64[us]
 5   order_delivered_carrier_date   96202 non-null  datetime64[us]
 6   order_delivered_customer_date  96203 non-null  datetime64[us]
 7   order_estimated_delivery_date  96203 non-null  datetime64[us]
 8   customer_unique_id             96203 non-null  str
 9   customer_zip_code_prefix       96203 non-null  int64
 10  customer_city                  96203 non-null  str
 11  customer_state                 96203 non-null  str
 12  delivery_days                  96203 non-null  int64
 13  is_late                        96203 non-null  bool
 14  days_vs_estimate               96203 non-null  int64
 15  purchase_month                 96203 non-null  period[M]
 16  promise_days                   96203 non-null  int64
 17  bucket                         96203 non-null  category
 18  review_id                      95560 non-null  str
 19  review_score                   95560 non-null  float64
 20  review_comment_title           11188 non-null  str
 21  review_comment_message         38718 non-null  str
 22  review_creation_date           95560 non-null  datetime64[us]
 23  review_answer_timestamp        95560 non-null  datetime64[us]
dtypes: bool(1), category(1), datetime64[us](7), float64(1), int64(4), period[M](1), str(9)
memory usage: 16.3 MB

In [30]:
group_by_review_score = orders_reviews.groupby('review_score', dropna=False).agg(orders_count=('order_id', 'count'))
group_by_review_score['pct'] = (group_by_review_score['orders_count'] / group_by_review_score['orders_count'].sum() * 100).round(2)

group_by_review_score

              orders_count    pct
review_score
1.0                   9314   9.68
2.0                   2914   3.03
3.0                   7897   8.21
4.0                  18843  19.59
5.0                  56592  58.83
NaN                    643   0.67

In [31]:
orders_reviews_notna = delivered.merge(reviews_by_order, on='order_id', how='inner')

orders_reviews_notna.info()

<class 'pandas.DataFrame'>
RangeIndex: 95560 entries, 0 to 95559
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       95560 non-null  str
 1   customer_id                    95560 non-null  str
 2   order_status                   95560 non-null  str
 3   order_purchase_timestamp       95560 non-null  datetime64[us]
 4   order_approved_at              95546 non-null  datetime64[us]
 5   order_delivered_carrier_date   95559 non-null  datetime64[us]
 6   order_delivered_customer_date  95560 non-null  datetime64[us]
 7   order_estimated_delivery_date  95560 non-null  datetime64[us]
 8   customer_unique_id             95560 non-null  str
 9   customer_zip_code_prefix       95560 non-null  int64
 10  customer_city                  95560 non-null  str
 11  customer_state                 95560 non-null  str
 12  delivery_days                  95560 non-null  int64
 13  is_late                        95560 non-null  bool
 14  days_vs_estimate               95560 non-null  int64
 15  purchase_month                 95560 non-null  period[M]
 16  promise_days                   95560 non-null  int64
 17  bucket                         95560 non-null  category
 18  review_id                      95560 non-null  str
 19  review_score                   95560 non-null  int64
 20  review_comment_title           11188 non-null  str
 21  review_comment_message         38718 non-null  str
 22  review_creation_date           95560 non-null  datetime64[us]
 23  review_answer_timestamp        95560 non-null  datetime64[us]
dtypes: bool(1), category(1), datetime64[us](7), int64(5), period[M](1), str(9)
memory usage: 16.2 MB

In [32]:
group_orders_reviews_notna = orders_reviews_notna.groupby('is_late').agg(
    orders_count=('order_id', 'count'),
    avg_review_score=('review_score', 'mean'),
    median_review_score=('review_score', 'median'),
    orders_with_score_1=('review_score', lambda a: (a == 1).sum()),
    orders_with_score_2=('review_score', lambda a: (a == 2).sum()),
)

group_orders_reviews_notna['pct_orders_with_score_1'] = (
    group_orders_reviews_notna['orders_with_score_1'] / group_orders_reviews_notna['orders_count'] * 100
).round(2)

group_orders_reviews_notna['pct_orders_with_score_2'] = (
    group_orders_reviews_notna['orders_with_score_2'] / group_orders_reviews_notna['orders_count'] * 100
).round(2)

group_orders_reviews_notna['avg_review_score'] = group_orders_reviews_notna['avg_review_score'].round(2)
group_orders_reviews_notna['median_review_score'] = group_orders_reviews_notna['median_review_score'].round(0).astype('int')

group_orders_reviews_notna

,orders_count,avg_review_score,median_review_score,orders_with_score_1,orders_with_score_2,pct_orders_with_score_1,pct_orders_with_score_2
is_late,,,,,,,
False,89182,4.29,5,5884,2364,6.60,2.65
True,6378,2.27,1,3430,550,53.78,8.62